### ISSUE TITLE
Add user type checking decorator

### ISSUE THREAD

**Issue by peterHoburg** [Python-Practice-Discord/template_python_discord_bot#13]
Add a decorator that will check to see if the user is a bot/has specific permissions.

This will also need users to have specific permission levels. A new DB table will need to be added. And some new columns.

**Comment by IrrationalBoolean** [comment]
https://discordpy.readthedocs.io/en/rewrite/ext/commands/api.html#discord.ext.commands.has_permissions

Might this decorator do for permission checks?

Also the user object has .bot to check if it is a bot.

https://discordpy.readthedocs.io/en/latest/api.html#discord.User.bot

**Comment by peterHoburg** [comment]
I think this would be the least complicated way to manage it. I will be adding a permission tier check that uses user roles and can be set at runtime in the config.ini file.
